### ISSUE TITLE
jar filename generated during mvn package cant be used by the supervisord start command

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#200]
## Issue

The jar filename of a quarkus application is different from a tornthail/vert.x/spring boot application `quarkus-rest-1.0-SNAPSHOT-runner.jar` and by consequence the supervisord `run` command fails to launch it

```

[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /usr/src/target/quarkus-rest-1.0-SNAPSHOT-runner.jar
--
  | [INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 3150ms
  | [INFO] ------------------------------------------------------------------------
  | [INFO] BUILD SUCCESS
  | [INFO] ------------------------------------------------------------------------
  | [INFO] Total time:  9.519 s
  | [INFO] Finished at: 2020-01-20T15:03:50Z
  | [INFO] ------------------------------------------------------------------------
  | cp: target '/deployments/app.jar' is not a directory
  | time="2020-01-20T15:03:50Z" level=error msg="program stopped with error:exit status 1" program=build
  | time="2020-01-20T15:03:50Z" level=info msg="success to start program" program=build
  | time="2020-01-20T15:03:50Z" level=debug msg="wait program exit" program=run
  | time="2020-01-20T15:03:50Z" level=error msg="program stopped with error:exit status 1" program=run
  | time="2020-01-20T15:03:50Z" level=info msg="success to start program" program=run
  | Error: Unable to access jarfile /deployments/app.jar
  | time="2020-01-20T15:03:51Z" level=debug msg="wait program exit" program=build
  | time="2020-01-20T15:03:51Z" level=debug msg="wait program exit" program=run
  | time="2020-01-20T15:03:51Z" level=error msg="program stopped with error:exit status 1" program=run
```

Nevertheless, the definition of the Quarkus runtime looks good

```
kc get runtimes/quarkus-1.1.1 -o yaml
apiVersion: halkyon.io/v1beta1
kind: Runtime
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"halkyon.io/v1beta1","kind":"Runtime","metadata":{"annotations":{},"name":"quarkus-1.1.1"},"spec":{"executablePattern":"*-runner","generator":"https://code.quarkus.io/api/download?g={{.GroupId}}\u0026a={{.ArtifactId}}\u0026v={{.ProjectVersion}}\u0026c={{.PackageName}}.ResourceExample","image":"quay.io/halkyonio/hal-maven-jdk","name":"quarkus","version":"1.1.1.Final"}}
  creationTimestamp: "2020-01-16T15:03:00Z"
  generation: 1
  name: quarkus-1.1.1
  resourceVersion: "6279190"
  selfLink: /apis/halkyon.io/v1beta1/runtimes/quarkus-1.1.1
  uid: 497e2201-3871-11ea-80bb-96000038fe55
spec:
  executablePattern: '*-runner'
  generator: https://code.quarkus.io/api/download?g={{.GroupId}}&a={{.ArtifactId}}&v={{.ProjectVersion}}&c={{.PackageName}}.ResourceExample
  image: quay.io/halkyonio/hal-maven-jdk
  name: quarkus
  version: 1.1.1.Final
```

## Reason

The `${JARPATTERN}` is gone from the Docker image used to perform the build within the supervisord's pod.

```
within the pod's container
$ env | grep JARPATTERN
JARPATTERN=*-runner

$ cat /usr/local/bin/build
#!/bin/bash

mvn -f /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/pom.xml ${MAVEN_ARGS} package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts && cp /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/target/*.jar /deployments/app.jar
```

If we built a new docker image for hal including the `JARPATTERN` env var within the build script 

```
#!/bin/sh

mvn -f /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/pom.xml ${MAVEN_ARGS} package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts && cp /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/target/${JARPATTERN}.jar /deployments/app.jar
```

and next we perform a `hal component push -c cc`, then the build will work like the `cp` step

@metacosm : Do you remember why you removed from `hal-maven-jdk` the ENV var `JARPATTERN` within the build script ?

**Comment by cmoulliard** [comment]
Content of the folder `/deployments` of the pod's supervisord

```
$ ls -la /deployments/
total 196
drwxrwx---. 19 root       root  4096 Jan 20 15:02 .
drwxr-xr-x.  1 root       root  4096 Jan 20 14:58 ..
-rw-r--r--.  1 1000200000 root  1156 Jan 20 15:01 README.md
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 aopalliance
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 backport-util-concurrent
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 classworlds
drwxr-xr-x.  8 1000200000 root  4096 Jan 20 15:02 com
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 commons-cli
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 commons-codec
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 commons-io
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 commons-lang
-rw-r--r--.  1 1000200000 root 67072 Jan 20 15:01 component.tar
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 15:02 io
drwxr-xr-x. 10 1000200000 root  4096 Jan 20 15:02 jakarta
drwxr-xr-x.  6 1000200000 root  4096 Jan 20 15:02 javax
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 jline
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 junit
-rwxr-xr-x.  1 1000200000 root 10078 Jan 20 15:01 mvnw
-rw-r--r--.  1 1000200000 root  6609 Jan 20 15:01 mvnw.cmd
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 15:02 net
drwxr-xr-x. 24 1000200000 root  4096 Jan 20 15:02 org
-rw-r--r--.  1 1000200000 root  4008 Jan 20 15:01 pom.xml
-rw-r--r--.  1 1000200000 root 19111 Jan 20 15:01 quarkus-rest.iml
drwxr-xr-x.  4 1000200000 root  4096 Jan 20 15:01 src
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 15:35 target
```

**Comment by iocanel** [comment]
Where is the JARPATTERN defined?

**Comment by cmoulliard** [comment]
> Where is the JARPATTERN defined?

here : https://github.com/halkyonio/operator/blob/4d20cc02f2486dd8d1b5f93653d960125fd797a5/deploy/runtimes.yaml#L31

**Comment by cmoulliard** [comment]
here is how supervisord is configured to build and run the image 

```
$ ls -la /var/lib/supervisord/conf/supervisor.conf
-rw-r--r--. 1 1000200000 1000200000 339 Jan 20 15:42 /var/lib/supervisord/conf/supervisor.conf
$ cat /var/lib/supervisord/conf/supervisor.conf
[program:build]
command = /usr/local/bin/build
autostart = false
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stdout
stdout_events_enabled = true

[program:run]
command = /usr/local/bin/run
autostart = true
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stdout
stdout_events_enabled = true

[inet_http_server]
port=localhost:9001$ cat /usr/local/bin/build
#!/bin/bash

mvn -f /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/pom.xml ${MAVEN_ARGS} package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts && cp /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/target/*.jar /deployments/app.jar
$
```

**Comment by cmoulliard** [comment]
Something wrong is happening within the Hetzner cloud machine as we have 2 java outofmemory process running

Remark : Does it affect our quarkus builld !!!

```
[root@halkyon1 ~]# ps -ef | grep java
1000200+ 10773 25785  2 17:29 ?        00:00:08 [java] <defunct>
1000190+ 15037 15036 12 17:34 ?        00:00:10 java -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
1000190+ 15262 15261 37 17:34 ?        00:00:22 java -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
1000200+ 15886 25785 28 17:35 ?        00:00:04 [java] <defunct>
root     16008 14423  0 17:35 pts/4    00:00:00 grep --color=auto java
```

**Comment by cmoulliard** [comment]
Command launched by the supervisord to do the maven build 
```
/usr/local/openjdk-8/bin/java -classpath /usr/share/maven/boot/plexus-classworlds-2.6.0.jar -Dclassworlds.conf=/usr/share/maven/bin/m2.conf -Dmaven.home=/usr/share/maven -Dlibrary.jansi.path=/usr/share/maven/lib/jansi-native -Dmaven.multiModuleProjectDirectory=/usr/src org.codehaus.plexus.classworlds.launcher.Launcher -f /usr/src///pom.xml package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts
```

**Comment by cmoulliard** [comment]
I dont know if this is related but the local maven repo is the same as code `/usr/src`
See
```
$ ls -la /usr/src
total 192
drwxrwx---. 19 root       root  4096 Jan 20 16:55 .
drwxr-xr-x.  1 root       root  4096 Sep 10 00:00 ..
-rw-r--r--.  1 1000200000 root  1156 Jan 20 16:54 README.md
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 aopalliance
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 backport-util-concurrent
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 classworlds
drwxr-xr-x.  8 1000200000 root  4096 Jan 20 16:55 com
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 commons-cli
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 commons-codec
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 commons-io
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 commons-lang
-rw-r--r--.  1 1000200000 root 67072 Jan 20 16:54 component.tar
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 16:54 io
drwxr-xr-x. 10 1000200000 root  4096 Jan 20 16:55 jakarta
drwxr-xr-x.  6 1000200000 root  4096 Jan 20 16:55 javax
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 jline
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 junit
-rwxr-xr-x.  1 1000200000 root 10078 Jan 20 16:54 mvnw
-rw-r--r--.  1 1000200000 root  6609 Jan 20 16:54 mvnw.cmd
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 net
drwxr-xr-x. 24 1000200000 root  4096 Jan 20 16:55 org
-rw-r--r--.  1 1000200000 root  4008 Jan 20 16:54 pom.xml
-rw-r--r--.  1 1000200000 root 19111 Jan 20 16:54 quarkus-rest.iml
drwxr-xr-x.  4 1000200000 root  4096 Jan 20 16:54 src
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 16:59 target
$ ls -la /tmp/artefacts
total 192
drwxrwx---. 19 root       root  4096 Jan 20 16:55 .
drwxrwxrwt.  1 root       root  4096 Sep 27 17:11 ..
-rw-r--r--.  1 1000200000 root  1156 Jan 20 16:54 README.md
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 aopalliance
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 backport-util-concurrent
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 classworlds
drwxr-xr-x.  8 1000200000 root  4096 Jan 20 16:55 com
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 commons-cli
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 commons-codec
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 commons-io
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 commons-lang
-rw-r--r--.  1 1000200000 root 67072 Jan 20 16:54 component.tar
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 16:54 io
drwxr-xr-x. 10 1000200000 root  4096 Jan 20 16:55 jakarta
drwxr-xr-x.  6 1000200000 root  4096 Jan 20 16:55 javax
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 jline
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:55 junit
-rwxr-xr-x.  1 1000200000 root 10078 Jan 20 16:54 mvnw
-rw-r--r--.  1 1000200000 root  6609 Jan 20 16:54 mvnw.cmd
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 16:54 net
drwxr-xr-x. 24 1000200000 root  4096 Jan 20 16:55 org
-rw-r--r--.  1 1000200000 root  4008 Jan 20 16:54 pom.xml
-rw-r--r--.  1 1000200000 root 19111 Jan 20 16:54 quarkus-rest.iml
drwxr-xr-x.  4 1000200000 root  4096 Jan 20 16:54 src
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 17:00 target
```

**Comment by cmoulliard** [comment]
Can one of you help me here as I dont understand why the bash cp command fails ? @metacosm @iocanel 

```
$
export CONTEXTPATH=.
export MODULEDIRNAME=.
mvn -f /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/pom.xml ${MAVEN_ARGS} package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< dev.snowdrop.quarkus:quarkus-rest >------------------
[INFO] Building quarkus-rest 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quarkus-rest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-rest ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ quarkus-rest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /usr/src/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-rest ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ quarkus-rest ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ quarkus-rest ---
[INFO]
[INFO] --- quarkus-maven-plugin:1.1.1.Final:build (default) @ quarkus-rest ---
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /usr/src/target/quarkus-rest-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 5851ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.000 s
[INFO] Finished at: 2020-01-20T17:20:31Z
[INFO] ------------------------------------------------------------------------
$ $ $ [INFO] Scanning for projects...
[INFO]
[INFO] -----------------< dev.snowdrop.quarkus:quarkus-rest >------------------
[INFO] Building quarkus-rest 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quarkus-rest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-rest ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /usr/src/././target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ quarkus-rest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /usr/src/././src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-rest ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /usr/src/././target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ quarkus-rest ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ quarkus-rest ---
[INFO] Building jar: /usr/src/././target/quarkus-rest-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:1.1.1.Final:build (default) @ quarkus-rest ---
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /usr/src/././target/quarkus-rest-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 6058ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.025 s
[INFO] Finished at: 2020-01-20T17:20:53Z
[INFO] ------------------------------------------------------------------------
$ ls -la /usr/src/././target/quarkus-rest-1.0-SNAPSHOT-runner.jar
-rw-r--r--. 1 1000200000 root 204130 Jan 20 17:20 /usr/src/././target/quarkus-rest-1.0-SNAPSHOT-runner.jar
$ cp /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/target/*.jar /deployments/app.jar
cp: target '/deployments/app.jar' is not a directory
$ ls -la /deployments
total 196
drwxrwx---. 19 root       root  4096 Jan 20 17:16 .
drwxr-xr-x.  1 root       root  4096 Jan 20 17:16 ..
-rw-r--r--.  1 1000200000 root  1156 Jan 20 17:16 README.md
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 aopalliance
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 backport-util-concurrent
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 classworlds
drwxr-xr-x.  8 1000200000 root  4096 Jan 20 17:16 com
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 commons-cli
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 commons-codec
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 commons-io
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 commons-lang
-rw-r--r--.  1 1000200000 root 67072 Jan 20 17:16 component.tar
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 17:16 io
drwxr-xr-x. 10 1000200000 root  4096 Jan 20 17:16 jakarta
drwxr-xr-x.  6 1000200000 root  4096 Jan 20 17:16 javax
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 jline
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 junit
-rwxr-xr-x.  1 1000200000 root 10078 Jan 20 17:16 mvnw
-rw-r--r--.  1 1000200000 root  6609 Jan 20 17:16 mvnw.cmd
drwxr-xr-x.  3 1000200000 root  4096 Jan 20 17:16 net
drwxr-xr-x. 24 1000200000 root  4096 Jan 20 17:16 org
-rw-r--r--.  1 1000200000 root  4008 Jan 20 17:16 pom.xml
-rw-r--r--.  1 1000200000 root 19111 Jan 20 17:16 quarkus-rest.iml
drwxr-xr-x.  4 1000200000 root  4096 Jan 20 17:16 src
drwxr-xr-x.  9 1000200000 root  4096 Jan 20 17:20 target
```

**Comment by iocanel** [comment]
@cmoulliard because `/deployments/` is not present. Make sure you crated it first.

**Comment by cmoulliard** [comment]
`/deployments` is well created. The problem is not there. 
I think that I know. The script of the `hal-maven-jdk` image pushed dont include anymore the ENV var JARPATTERN`

Look
```
within the pod's container
$ env | grep JARPATTERN
JARPATTERN=*-runner

$ cat /usr/local/bin/build
#!/bin/bash

mvn -f /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/pom.xml ${MAVEN_ARGS} package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts && cp /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/target/*.jar /deployments/app.jar
```
but `build` bash file defined within the github project includes an ENV var
https://raw.githubusercontent.com/halkyonio/container-images/master/hal-mvn-jdk/build

@iocanel Can you check how the `build` file pushed on the docker image looks like ?

**Comment by cmoulliard** [comment]
My assumption was correct. I built a new docker image for hal including the `JARPATTERN` env var and now, maven build is working correctly + cp step 

```
time="2020-01-20T17:42:45Z" level=info msg="success to start program" program=run
--
  | Exception in thread "main" java.lang.NoClassDefFoundError: io/quarkus/runtime/Application
  | at java.lang.ClassLoader.defineClass1(Native Method)
  | at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  | at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  | at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  | at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  | at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  | at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  | at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:27)
```
REMARK: There is another java error which is certainly related to the fact that we dont build correctllyy the Quarkus application

**Comment by cmoulliard** [comment]
Can we start quarkus using this command @aureamunoz @geoand ? Why: See error reported within the previous comment `Exception in thread "main" java.lang.NoClassDefFoundError: io/quarkus/runtime/Application`
```
java -XX:+UseParallelOldGC \
     -XX:MinHeapFreeRatio=10 \
     -XX:MaxHeapFreeRatio=20 \
     -XX:GCTimeRatio=4 \
     -XX:AdaptiveSizePolicyWeight=90 \
     -XX:MaxMetaspaceSize=100m \
     -XX:+ExitOnOutOfMemoryError \
     -cp "." -jar /deployments/app.jar
```

**Comment by geoand** [comment]
The most likely cause is that an Uber jar is not being built, but instead a thin jar is probably being used.

https://quarkus.io/guides/maven-tooling#uber-jar-maven

**Comment by metacosm** [comment]
> @metacosm : Do you remember why you removed from `hal-maven-jdk` the ENV var `JARPATTERN` within the build script ?

It is not removed, see: https://github.com/halkyonio/container-images/blob/master/hal-mvn-jdk/build#L3. I think the issue is maybe that we're not pulling the proper tag?

**Comment by cmoulliard** [comment]
> I think the issue is maybe that we're not pulling the proper tag?

 No idea but the latest image pushed on quay didn't included the `JARPATTERN` env var

**Comment by cmoulliard** [comment]
> a thin jar is probably being used.

I added the following `MAVEN_ARGS` to the `hal-maven-jdk` and that works
```
-Dquarkus.package.uber-jar=true
```

**Comment by iocanel** [comment]
@cmoulliard: So, is the issue now resolved? Anything additional needs to be done?

**Comment by cmoulliard** [comment]
I pushed a new docker build of the `hal-maven-jdk` image to fix that issue 

```
TAG_ID=$(docker images -q hal)
docker tag $TAG_ID quay.io/halkyonio/hal-maven-jdk
docker push quay.io/halkyonio/hal-maven-jdk
docker push quay.io/halkyonio/hal-maven-jdk
The push refers to repository [quay.io/halkyonio/hal-maven-jdk]
88dfb6a8528b: Layer already exists 
ba929019d01d: Layer already exists 
3cc09e44203a: Layer already exists 
a641842b7677: Layer already exists 
0f7cb3d1bf25: Layer already exists 
9ce502d2508e: Layer already exists 
8f722f32d1be: Layer already exists 
304891580fb1: Layer already exists 
3e0fa1b47635: Layer already exists 
2492b0ca57f8: Layer already exists 
fbc3b2dba006: Layer already exists 
dfc3c372b2bb: Layer already exists 
831c5620387f: Layer already exists 
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
latest: digest: sha256:d85567d1f3a63d9dbf88dbbd65b3b2a45c6846ad28811f3837da77a61654235a size: 19855
```

**Comment by metacosm** [comment]
Is this fixed then?

**Comment by cmoulliard** [comment]
> So, is the issue now resolved? Anything additional needs to be done?

yes and no further action is needed at the moment
